spring:
  sql:
    init:
      mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: task-api
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

