### Project 생성
POST localhost:6060/?adminId=asd
Content-Type: application/json

{
  "projectName": "sample",
  "projectStatus": "ACTIVE"
}

### Project 생성
POST localhost:6060/?adminId=asd
Content-Type: application/json

{
  "projectName": "sample2",
  "projectStatus": "ACTIVE"
}

### 프로젝트 조회
GET localhost:6060/1
Accept: application/json

###
PUT localhost:6060/1
Content-Type: application/json

{
  "projectName": "sampleee",
  "projectStatus": "ACTIVE"
}

###
GET localhost:6060/?adminId=asd
Accept: application/json

###
DELETE localhost:6060/1
Accept: application/json


### Tag CRUD
### Tag 생성
POST localhost:6060/1/tag
Content-Type: application/json

{
  "tagName": "testTag1"
}

### Tag 생성
POST localhost:6060/2/tag
Content-Type: application/json

{
  "tagName": "testTag2"
}

### Tag 조회
GET localhost:6060/2/tag
Accept: application/json

### Tag 수정
PUT localhost:6060/1/tag
Content-Type: application/json

{
  "tagName": "tag수정"
}

### Tag 삭제
DELETE localhost:6060/1/tag
Accept: application/json