### 전체 Task 목록 조회 (project id: 1)
GET http://localhost:6060/1/
Accept: application/json

### Task 등록 (project id: 1)
POST http://localhost:6060/1/?userId=me
Content-Type: application/json

{
  "taskName": "NHN아카데미 미니프로젝트",
  "userId": "me",
  "managerId": "NHNacademy"
}

### 단일 Task 조회 (project id: 1, task id: 1)
GET http://localhost:6060/1/2
Accept: application/json

### Task 수정 (project id: 1, task id: 1)
PUT http://localhost:6060/1/1
Content-Type: application/json

{
  "taskName": "task 기능 작성",
  "managerId": "task0202"
}

### Task 삭제 (project id: 1, task id: 1)
DELETE http://localhost:6060/1/1
Accept: application/json


### Tag
### Task에 Tag 등록 (project id: 1, task id: 2, tag id: 3)
POST localhost:6060/1/2/tag/3
Accept: application/json

### Task에 설정 되어있는 Tag 조회 (project id: 1, task id: 2)
GET localhost:6060/1/2/tag
Accept: application/json

### Task에 설정된 Tag 삭제 (project id: 1, task id: 2, tag id: 3)
DELETE localhost:6060/1/2/tag/3
Accept: application/json


### MileStone
### Task에 MileStone 등록 (project id: 1, task id: 2, milestone id: 2)
POST localhost:6060/1/2/milestone/2
Accept: application/json

### Task에 설정 되어있는 MileStone 조회 (project id: 1, task id: 2)
GET localhost:6060/1/2/milestone
Accept: application/json

### Task에 설정된 MileStone 삭제 (project id: 1, task id: 2)
DELETE localhost:6060/1/2/milestone